import type { AgentActionProposal, JsonValue } from "@alignment-governance-stack/shared-types";
import type { ApprovalEvidence, AuthorityMap } from "./types.js";

/** Source evidence only. Identity recognition belongs to the trusted host. */
export interface HumanExpression {
  id: string;
  humanId: string;
  text: string;
  expressedAt: string;
}

export interface ClarificationRequirement {
  id: string;
  kind: "missing_information" | "ambiguity" | "conflicting_instructions" | "preference_uncertainty" | "authority_uncertainty";
  question: string;
}

export interface IntentProposal {
  id: string;
  status: "provisional";
  expressionId: string;
  objective: string;
  parameters: Record<string, JsonValue>;
  preferences: Record<string, JsonValue>;
  constraints: string[];
  unresolved: ClarificationRequirement[];
  /** Descriptive only; never an establishment condition. */
  confidence: number;
}

export type DelegationState = "task_initiated" | "clarification_required" | "interpretation_proposed"
  | "confirmation_required" | "authority_established" | "authority_rejected" | "authority_expired" | "authority_revoked";

export interface DelegationOrigin {
  kind: "explicit_expression" | "standing_delegation" | "permitted_preference" | "inference_awaiting_confirmation";
  sourceId: string;
  /** JSON Pointer: embedded expression locations are resolved by Core; other sources remain host-owned.
   * Structural resolution is not semantic entailment or authentication. */
  pointer: string;
}

export interface DelegationProposal {
  version: "delegation-proposal/v1";
  id: string;
  expression: HumanExpression;
  intent: IntentProposal;
  delegateId: string;
  consequence: "low" | "high";
  /** Finite, exact candidates. Objective and preferences never expand this list. */
  permittedActions: AgentActionProposal[];
  prohibitedActionTypes: string[];
  discretion: "none" | "choose_listed_action";
  /** Phase 1 deliberately does not issue transitive authority. */
  delegationRights: "none";
  approvalRequirement: "confirmed_exact_actions";
  standing: boolean;
  /** Optional confirmed conditions; distinct from the recurrence flag above. */
  currentStanding?: import("./standingTypes.js").StandingContract;
  /** Explicit opt-in; bound by the same whole-envelope confirmation. */
  executionRevalidation?: import("./executionRevalidationPolicy.js").ExecutionRevalidationPolicy;
  validFrom: string;
  expiresAt: string;
  /** Absolute half-open windows. Hosts expand calendars before confirmation. */
  activeWindows: { startsAt: string; endsAt: string }[];
  revocationCondition: "human_revocation_or_host_withdrawal";
  /** Every leaf outside this map must have a retained origin. */
  provenance: Record<string, DelegationOrigin>;
}

/** Trusted host attestation to a human's explicit review of this whole envelope.
 * Not extracted from expression text, generated by confidence, or a signature. */
export interface DelegationConfirmation {
  /** Host-issued unique authorization event ID. Never reuse for another human decision. */
  id: string;
  humanId: string;
  proposalDigest: string;
  decision: "confirm" | "reject";
  confirmedAt: string;
  approvals: ApprovalEvidence[];
}

export interface EstablishedDelegation {
  version: "established-delegation/v1";
  state: "authority_established";
  proposal: DelegationProposal;
  confirmation: DelegationConfirmation;
  establishedAt: string;
  digest: string;
}

export interface DelegationRevocation {
  /** Stable across repeated establishment of the same human confirmation event. */
  authorizationEventId: string;
  delegationId: string;
  delegationDigest: string;
  expression: HumanExpression;
  revokedAt: string;
}

export interface DelegationHostContext {
  /** Complete host-owned history, required at establishment as well as current validation. */
  revocations: readonly DelegationRevocation[];
  now: string;
  authorityMap: AuthorityMap;
  /** Host-authenticated identity; never selected by untrusted proposed content. */
  humanId: string;
  /** Retained non-expression evidence, including preferences or historical grants. */
  sourceIds: string[];
  /** Host floor; a proposed low consequence cannot override it. */
  minimumConsequence: "low" | "high";
}

export interface CurrentDelegationContext extends DelegationHostContext {
  delegateId: string;
  /** Host's current registry, not a registry supplied inside the artifact. */
  establishedDigests: Readonly<Record<string, string>>;
}
